[env:recovery]
platform = espressif32@6.9.0
board = dfrobot_firebeetle2_esp32e
framework = arduino
monitor_speed = 115200
board_upload.flash_size = 16MB
board_build.partitions = ../fw/partitions.csv
board_build.filesystem = littlefs
board_build.flash_mode = dio
build_flags =
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    tzapu/WiFiManager@^2.0.17
